In [4]:
import pandas as pd
import numpy as np
from path_config import PathConfig

In [5]:
paths = PathConfig()

In [6]:
ul_data = pd.read_excel(paths.ul_path, sheet_name='Series Formatted Data')
dl_data = pd.read_excel(paths.dl_path, sheet_name='Series Formatted Data')
bs_data = pd.read_excel(paths.Hucre_Bilgileri, sheet_name='Hücre tablosu')
scanner_data = pd.read_excel(paths.scanner_path, sheet_name='Series Formatted Data')

In [7]:
set(
    list(scanner_data["NR_Scan_PCI_SortedBy_RSRP_0"].dropna().unique().astype(int)) + \
    list(scanner_data["NR_Scan_PCI_SortedBy_RSRP_1"].dropna().unique().astype(int)) + \
    list(scanner_data["NR_Scan_PCI_SortedBy_RSRP_2"].dropna().unique().astype(int)) + \
    list(scanner_data["NR_Scan_PCI_SortedBy_RSRP_3"].dropna().unique().astype(int)) + \
    list(scanner_data["NR_Scan_PCI_SortedBy_RSRP_4"].dropna().unique().astype(int)) + \
    list(scanner_data["NR_Scan_PCI_SortedBy_RSRP_5"].dropna().unique().astype(int)) + \
    list(scanner_data["NR_Scan_PCI_SortedBy_RSRP_6"].dropna().unique().astype(int)) + \
    
    list(dl_data["NR_UE_PCI_0"].dropna().unique().astype(int)) + \
    list(dl_data["NR_UE_Nbr_PCI_0"].dropna().unique().astype(int)) + \
    list(dl_data["NR_UE_Nbr_PCI_1"].dropna().unique().astype(int)) + \
    list(dl_data["NR_UE_Nbr_PCI_2"].dropna().unique().astype(int)) + \
    list(dl_data["NR_UE_Nbr_PCI_3"].dropna().unique().astype(int)) + \
    list(dl_data["NR_UE_Nbr_PCI_4"].dropna().unique().astype(int)) + \

    list(ul_data["NR_UE_PCI_0"].dropna().unique().astype(int)) + \
    list(ul_data["NR_UE_Nbr_PCI_0"].dropna().unique().astype(int)) + \
    list(ul_data["NR_UE_Nbr_PCI_1"].dropna().unique().astype(int)) + \
    list(ul_data["NR_UE_Nbr_PCI_2"].dropna().unique().astype(int)) + \
    list(ul_data["NR_UE_Nbr_PCI_3"].dropna().unique().astype(int)) + \
    list(ul_data["NR_UE_Nbr_PCI_4"].dropna().unique().astype(int))) \
        - set(list(bs_data["PCI "].dropna().unique().astype(int)) )

{np.int64(38),
 np.int64(246),
 np.int64(278),
 np.int64(442),
 np.int64(443),
 np.int64(444),
 np.int64(445)}

In [8]:
set(ul_data["NR_UE_PCI_0"].unique()) - set(bs_data["PCI "].unique())

{np.float64(38.0), np.float64(246.0), np.float64(278.0), np.float64(nan)}

In [9]:
scanner_data[[col for col in scanner_data.columns if col not in ("Time", "Longitude", "Latitude", "Message")]]

,NR_Scan_NR_ARFCN,NR_Scan_PCI_SortedBy_RSRP_0,NR_Scan_PCI_SortedBy_RSRP_1,NR_Scan_PCI_SortedBy_RSRP_2,NR_Scan_PCI_SortedBy_RSRP_3,NR_Scan_PCI_SortedBy_RSRP_4,NR_Scan_PCI_SortedBy_RSRP_5,NR_Scan_PCI_SortedBy_RSRP_6,Unnamed: 12,NR_Scan_SSB_RSRP_SortedBy_RSRP_0,...,NR_Scan_SSB_RSRQ_SortedBy_RSRP_5,NR_Scan_SSB_RSRQ_SortedBy_RSRP_6,Unnamed: 28,NR_Scan_SSB_SINR_SortedBy_RSRP_0,NR_Scan_SSB_SINR_SortedBy_RSRP_1,NR_Scan_SSB_SINR_SortedBy_RSRP_2,NR_Scan_SSB_SINR_SortedBy_RSRP_3,NR_Scan_SSB_SINR_SortedBy_RSRP_4,NR_Scan_SSB_SINR_SortedBy_RSRP_5,NR_Scan_SSB_SINR_SortedBy_RSRP_6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22387,640704.0,68.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,-114.03,...,NaN,NaN,NaN,-8.14,-12.25,NaN,NaN,NaN,NaN,NaN
22388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
scanner_data.dropna(subset=[col for col in scanner_data.columns if col not in ("Time", "Longitude", "Latitude", "Message")], how='all')

,Message,Time,Longitude,Latitude,NR_Scan_NR_ARFCN,NR_Scan_PCI_SortedBy_RSRP_0,NR_Scan_PCI_SortedBy_RSRP_1,NR_Scan_PCI_SortedBy_RSRP_2,NR_Scan_PCI_SortedBy_RSRP_3,NR_Scan_PCI_SortedBy_RSRP_4,...,NR_Scan_SSB_RSRQ_SortedBy_RSRP_5,NR_Scan_SSB_RSRQ_SortedBy_RSRP_6,Unnamed: 28,NR_Scan_SSB_SINR_SortedBy_RSRP_0,NR_Scan_SSB_SINR_SortedBy_RSRP_1,NR_Scan_SSB_SINR_SortedBy_RSRP_2,NR_Scan_SSB_SINR_SortedBy_RSRP_3,NR_Scan_SSB_SINR_SortedBy_RSRP_4,NR_Scan_SSB_SINR_SortedBy_RSRP_5,NR_Scan_SSB_SINR_SortedBy_RSRP_6
30,30,2025-03-14 12:14:37.849,29.02949,41.10723,640704.0,48.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.80,NaN,NaN,NaN,NaN,NaN,NaN
33,33,2025-03-14 12:14:38.309,29.02949,41.10723,640704.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,36,2025-03-14 12:14:38.374,29.02949,41.10723,640704.0,48.0,76.0,NaN,NaN,NaN,...,NaN,NaN,NaN,14.31,-18.22,NaN,NaN,NaN,NaN,NaN
38,38,2025-03-14 12:14:38.410,29.02949,41.10723,640704.0,48.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,11.23,NaN,NaN,NaN,NaN,NaN,NaN
43,43,2025-03-14 12:14:38.730,29.02949,41.10723,640704.0,48.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,12.03,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22378,22378,2025-03-14 12:32:16.677,29.02143,41.10030,640704.0,68.0,59.0,NaN,NaN,NaN,...,NaN,NaN,NaN,-8.44,-14.02,NaN,NaN,NaN,NaN,NaN
22380,22380,2025-03-14 12:32:16.777,29.02143,41.10030,643296.0,278.0,246.0,38.0,NaN,NaN,...,NaN,NaN,NaN,27.39,-11.15,-17.48,NaN,NaN,NaN,NaN
22382,22382,2025-03-14 12:32:16.779,29.02143,41.10030,643296.0,278.0,246.0,38.0,NaN,NaN,...,NaN,NaN,NaN,27.88,-10.21,-18.95,NaN,NaN,NaN,NaN
22385,22385,2025-03-14 12:32:16.899,29.02143,41.10030,643296.0,278.0,246.0,38.0,NaN,NaN,...,NaN,NaN,NaN,26.29,-11.15,-16.13,NaN,NaN,NaN,NaN
22387,22387,2025-03-14 12:32:16.957,29.02143,41.10030,640704.0,68.0,59.0,NaN,NaN,NaN,...,NaN,NaN,NaN,-8.14,-12.25,NaN,NaN,NaN,NaN,NaN

In [11]:
ul_data.dropna(subset=[col for col in ul_data.columns if (col not in ("Time", "Longitude", "Latitude", "Message", "Technology_Mode") 
                                            and set(ul_data[col].dropna().unique()) != {0, 1})], how='all')

,Message,Time,Longitude,Latitude,Technology_Mode,NR_UE_PCI_0,NR_UE_RSRP_0,NR_UE_RSRQ_0,NR_UE_SINR_0,NR_UE_Nbr_PCI_0,...,Unnamed: 48,NR_UE_RRCConnectionComplete,NR_UE_RRCConnectionDrop,NR_UE_RRCHOAttempt,NR_UE_RRCHOOK,NR_RRC_MsgType,NAS_5GS_MM_MessageType,Unnamed: 55,NR_UE_Throughput_RLC_UL,App_Throughput_UL
1,1,2025-03-14 12:14:33.135,NaN,NaN,5GSA,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN
7,7,2025-03-14 12:14:33.499,29.02949,41.10723,5GSA,48.0,-80.7,-10.5,12.0,76.0,...,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN
12,12,2025-03-14 12:14:33.499,29.02949,41.10723,5GSA,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN
17,17,2025-03-14 12:14:33.499,29.02949,41.10723,5GSA,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN
28,28,2025-03-14 12:14:33.581,29.02949,41.10723,5GSA,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59740,59740,2025-03-14 12:32:09.648,29.02145,41.10029,5GSA,68.0,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN
59741,59741,2025-03-14 12:32:09.648,29.02145,41.10029,5GSA,68.0,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,BCCH-BCH MIB,NaN,NaN,NaN,NaN
59742,59742,2025-03-14 12:32:09.648,29.02145,41.10029,5GSA,68.0,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,BCCH-DL_SCH SIB1,NaN,NaN,NaN,NaN
59747,59747,2025-03-14 12:32:10.018,29.02145,41.10029,5GSA,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN
59785,59785,2025-03-14 12:32:15.915,29.02143,41.10030,5GSA,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0.0

In [12]:
ul_data[[col for col in ul_data.columns if (col not in ("Time", "Longitude", "Latitude", "Message", "Technology_Mode") 
                                            and set(ul_data[col].dropna().unique()) != {0, 1})]]

,NR_UE_PCI_0,NR_UE_RSRP_0,NR_UE_RSRQ_0,NR_UE_SINR_0,NR_UE_Nbr_PCI_0,NR_UE_Nbr_PCI_1,NR_UE_Nbr_PCI_2,NR_UE_Nbr_PCI_3,NR_UE_Nbr_PCI_4,NR_UE_Nbr_RSRP_0,...,NR_UE_Power_Tx_PRACH_0,NR_UE_NACK_Rate_UL_0,NR_UE_RACH_Procedure_Count,NR_UE_RRCReEst_EndResult,Unnamed: 48,NR_RRC_MsgType,NAS_5GS_MM_MessageType,Unnamed: 55,NR_UE_Throughput_RLC_UL,App_Throughput_UL
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
ul_data[[col for col in ul_data.columns if set(ul_data[col].unique()) == {0, 1}]]

,NR_UE_RACH_Attempt,NR_UE_RACH_OK,NR_UE_RACH_Fail,NR_UE_RRCReEstAttempt,NR_UE_RRCReEstFail,NR_UE_RRCConnectionAttempt,NR_UE_RRCConnectionSetupOk,NR_UE_RRCConnectionComplete,NR_UE_RRCConnectionDrop,NR_UE_RRCHOAttempt,NR_UE_RRCHOOK
0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
59803,0,0,0,0,0,0,0,0,0,0,0
59804,0,0,0,0,0,0,0,0,0,0,0
59805,0,0,0,0,0,0,0,0,0,0,0
59806,0,0,0,0,0,0,0,0,0,0,0
59807,0,0,0,0,0,0,0,0,0,0,0

In [14]:
set(scanner_data.columns.str[:26])

{'Latitude',
 'Longitude',
 'Message',
 'NR_Scan_NR_ARFCN',
 'NR_Scan_PCI_SortedBy_RSRP_',
 'NR_Scan_SSB_RSRP_SortedBy_',
 'NR_Scan_SSB_RSRQ_SortedBy_',
 'NR_Scan_SSB_SINR_SortedBy_',
 'Time',
 'Unnamed: 12',
 'Unnamed: 20',
 'Unnamed: 28'}

In [15]:
set(ul_data.columns.str[:14])

{'App_Throughput',
 'Latitude',
 'Longitude',
 'Message',
 'NAS_5GS_MM_Mes',
 'NR_RRC_MsgType',
 'NR_UE_Ack_As_N',
 'NR_UE_BLER_DL_',
 'NR_UE_CCE_Aggr',
 'NR_UE_MCS_DL_0',
 'NR_UE_Modulati',
 'NR_UE_NACK_Rat',
 'NR_UE_Nbr_PCI_',
 'NR_UE_Nbr_RSRP',
 'NR_UE_Nbr_RSRQ',
 'NR_UE_PCI_0',
 'NR_UE_Pathloss',
 'NR_UE_Power_Tx',
 'NR_UE_RACH_Att',
 'NR_UE_RACH_Fai',
 'NR_UE_RACH_OK',
 'NR_UE_RACH_Pro',
 'NR_UE_RB_Num_D',
 'NR_UE_RI_DL_0',
 'NR_UE_RRCConne',
 'NR_UE_RRCHOAtt',
 'NR_UE_RRCHOOK',
 'NR_UE_RRCReEst',
 'NR_UE_RSRP_0',
 'NR_UE_RSRQ_0',
 'NR_UE_SINR_0',
 'NR_UE_Throughp',
 'NR_UE_Timing_A',
 'Technology_Mod',
 'Time',
 'Unnamed: 27',
 'Unnamed: 48',
 'Unnamed: 55'}

In [16]:
full_data = pd.read_parquet(paths.parquet_data)