In [6]:
import polars as pl
from path_config import PathConfig
paths = PathConfig()

In [ ]:
dl_data = pl.read_excel(paths.dl_path, sheet_name='Series Formatted Data')
dl_data = dl_data.drop(["Message", "Technology_Mode"])

Could not determine dtype for column 10, falling back to string
Could not determine dtype for column 11, falling back to string
Could not determine dtype for column 12, falling back to string
Could not determine dtype for column 13, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 16, falling back to string
Could not determine dtype for column 17, falling back to string
Could not determine dtype for column 18, falling back to string
Could not determine dtype for column 20, falling back to string
Could not determine dtype for column 21, falling back to string
Could not determine dtype for column 22, falling back to string
Could not determine dtype for column 23, falling back to string
Could not determine dtype for column 24, falling back to string
Could not determine dtype for column 27, falling back to string
Could not determine dtype for column 28, falling back to string
Could not determine dtype for column 29, falling back to string
Could not determine dtype for column 30, falling back to string
Could not determine dtype for column 31, falling back to string
Could not determine dtype for column 32, falling back to string
Could not determine dtype for column 34, falling back to string
Could not determine dtype for column 35, falling back to string
Could not determine dtype for column 37, falling back to string
Could not determine dtype for column 42, falling back to string
Could not determine dtype for column 45, falling back to string
Could not determine dtype for column 48, falling back to string
Could not determine dtype for column 53, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 55, falling back to string

In [68]:
def dl_group_by_col(data, columns):

    if isinstance(columns, str):
        columns = [columns]
    
    new_data = pl.DataFrame()

    last_known_data_cols = ['Longitude', 'Latitude','NR_UE_PCI_0','NR_UE_Nbr_PCI_0', 'NR_UE_Nbr_PCI_1',
                           'NR_UE_Nbr_PCI_2', 'NR_UE_Nbr_PCI_3', 'NR_UE_Nbr_PCI_4', 'NR_UE_NACK_Rate_DL_0',
                           'NR_UE_Ack_As_Nack_DL_0', 'NR_UE_MCS_DL_0', 'NR_UE_RB_Num_DL_0',
                           'NR_UE_Modulation_Avg_DL_0', 'NR_UE_RI_DL_0', 'NR_UE_BLER_DL_0',
                           'NR_UE_CCE_AggregationLev_0', 'NR_UE_Power_Tx_PUSCH_0',
                           'NR_UE_Power_Tx_PRACH_0', 'NR_UE_NACK_Rate_UL_0', 'NR_UE_RACH_Attempt',
                           'NR_UE_RACH_OK', 'NR_UE_RACH_Fail', 'NR_UE_RACH_Procedure_Count', 'NR_UE_RRCReEstAttempt',
                           'NR_UE_RRCReEstFail', 'NR_UE_RRCReEst_EndResult', 'NR_UE_RRCConnectionAttempt',
                           'NR_UE_RRCConnectionSetupOk', 'NR_UE_RRCConnectionComplete',
                           'NR_UE_RRCConnectionDrop', 'NR_UE_RRCHOAttempt', 'NR_UE_RRCHOOK',
                           'NR_RRC_MsgType', 'NAS_5GS_MM_MessageType', 'NAS_5GS_SM_MessageType']
    
    mean_cols = ['NR_UE_RSRP_0', 'NR_UE_RSRQ_0', 'NR_UE_SINR_0','NR_UE_Nbr_RSRP_0', 'NR_UE_Nbr_RSRP_1', 'NR_UE_Nbr_RSRP_2',
                'NR_UE_Nbr_RSRP_3', 'NR_UE_Nbr_RSRP_4', 'NR_UE_Nbr_RSRQ_0','NR_UE_Nbr_RSRQ_1', 'NR_UE_Nbr_RSRQ_2', 'NR_UE_Nbr_RSRQ_3',
                'NR_UE_Nbr_RSRQ_4', 'NR_UE_Pathloss_DL_0','NR_UE_Timing_Advance',
                'NR_UE_Throughput_PDCP_DL', 'App_Throughput_DL']
    

    for column in columns:
        if column in last_known_data_cols:
            last_known_data_cols.remove(column)
        if column in mean_cols:
            mean_cols.remove(column)
    
    new_data = data.group_by("Time").agg([
        pl.col(mean_cols).mean(),
        pl.col(last_known_data_cols).forward_fill().last()
    ])

    last_known_data_cols = list(set(last_known_data_cols) - set(["Longitude","Latitude"]))
    mean_cols.append("Time")

    new_data = data.group_by(["Longitude","Latitude"]).agg([
        pl.col(mean_cols).mean(),
        pl.col(last_known_data_cols).drop_nulls().last()
    ])
    
    return new_data

In [69]:
df = dl_group_by_col(dl_data, "Time")
df

shape: (1_515, 53)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Longitude ┆ Latitude ┆ NR_UE_RSR ┆ NR_UE_RSR ┆ … ┆ NR_UE_Ack ┆ NR_UE_NAC ┆ NR_UE_RRC ┆ NR_UE_RAC │
│ ---       ┆ ---      ┆ P_0       ┆ Q_0       ┆   ┆ _As_Nack_ ┆ K_Rate_DL ┆ Connectio ┆ H_Attempt │
│ f64       ┆ f64      ┆ ---       ┆ ---       ┆   ┆ DL_0      ┆ _0        ┆ nAttempt  ┆ ---       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i64       │
│           ┆          ┆           ┆           ┆   ┆ str       ┆ str       ┆ i64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 29.02779  ┆ 41.10613 ┆ -70.2     ┆ -10.4     ┆ … ┆ 0         ┆ 11.5      ┆ 0         ┆ 0         │
│ 29.01833  ┆ 41.10173 ┆ -132.1    ┆ -23.9     ┆ … ┆ 27        ┆ 11.9      ┆ 0         ┆ 0         │
│ 29.0254   ┆ 41.10781 ┆ -92.25    ┆ -11.4     ┆ … ┆ 0         ┆ 9.3       ┆ 0         ┆ 0         │
│ 29.02547  ┆ 41.10507 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 0         ┆ 0         │
│ 29.02555  ┆ 41.10781 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 8.2       ┆ 0         ┆ 0         │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 29.01536  ┆ 41.10588 ┆ -121.9    ┆ -16.35    ┆ … ┆ 1         ┆ 18.5      ┆ 0         ┆ 0         │
│ 29.03115  ┆ 41.09978 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 0         ┆ 0         │
│ 29.02443  ┆ 41.10785 ┆ -73.0     ┆ -10.4     ┆ … ┆ 0         ┆ 3         ┆ 0         ┆ 0         │
│ 29.02063  ┆ 41.10786 ┆ -106.4    ┆ -13.3     ┆ … ┆ 0         ┆ 12.2      ┆ 0         ┆ 0         │
│ 29.02795  ┆ 41.10625 ┆ -82.2     ┆ -10.5     ┆ … ┆ 0         ┆ 7.3       ┆ 0         ┆ 0         │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [87]:
df.sort("Time")

shape: (1_515, 53)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Longitude ┆ Latitude ┆ NR_UE_RSR ┆ NR_UE_RSR ┆ … ┆ NR_UE_Ack ┆ NR_UE_NAC ┆ NR_UE_RRC ┆ NR_UE_RAC │
│ ---       ┆ ---      ┆ P_0       ┆ Q_0       ┆   ┆ _As_Nack_ ┆ K_Rate_DL ┆ Connectio ┆ H_Attempt │
│ f64       ┆ f64      ┆ ---       ┆ ---       ┆   ┆ DL_0      ┆ _0        ┆ nAttempt  ┆ ---       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i64       │
│           ┆          ┆           ┆           ┆   ┆ str       ┆ str       ┆ i64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ null      ┆ null     ┆ -87.1     ┆ -11.2     ┆ … ┆ null      ┆ null      ┆ 0         ┆ 0         │
│ 29.02949  ┆ 41.10723 ┆ -87.17333 ┆ -10.9     ┆ … ┆ 0         ┆ 8.6       ┆ 0         ┆ 0         │
│           ┆          ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 29.02947  ┆ 41.10722 ┆ -88.95    ┆ -11.15    ┆ … ┆ 0         ┆ 9.9       ┆ 0         ┆ 0         │
│ 29.02944  ┆ 41.10724 ┆ -89.35    ┆ -11.35    ┆ … ┆ 0         ┆ 8.4       ┆ 0         ┆ 0         │
│ 29.02941  ┆ 41.10725 ┆ -91.65    ┆ -12.3     ┆ … ┆ 0         ┆ 9.8       ┆ 0         ┆ 0         │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 29.02147  ┆ 41.10027 ┆ -118.55   ┆ -13.15    ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 29.02146  ┆ 41.10028 ┆ -118.15   ┆ -12.65    ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 29.02145  ┆ 41.10029 ┆ -118.7833 ┆ -13.68333 ┆ … ┆ 0         ┆ 33.3      ┆ 0         ┆ 0         │
│           ┆          ┆ 33        ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 29.02143  ┆ 41.1003  ┆ -118.21   ┆ -13.31    ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 29.02143  ┆ 41.10031 ┆ -119.6    ┆ -13.6     ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [113]:
pl.Config.set_tbl_rows(-1)     # Sınırsız satır
pl.Config.set_tbl_cols(-1)     # Sınırsız sütun
pl.Config.set_tbl_width_chars(2000)  # Geniş ekran
from datetime import datetime, timedelta
for row in df.filter(pl.col("NR_UE_Pathloss_DL_0").is_null()).iter_rows(named=True):
    
    
    target_time = row["Time"]

    # 1 dakika öncesi ve sonrası
    oncesi = target_time - timedelta(seconds=10)
    sonrasi = target_time + timedelta(seconds=10)

    context_data = df.filter(
        (pl.col("Time") >= oncesi) & 
        (pl.col("Time") <= sonrasi)
    ).sort("Time")

    print(context_data["Time","Longitude","Latitude", "NR_UE_PCI_0","NR_UE_Nbr_PCI_1","NR_UE_RSRP_0", "NR_UE_RSRQ_0", "NR_UE_SINR_0","NR_UE_Pathloss_DL_0", 'NR_UE_Nbr_RSRP_1'])

shape: (32, 10)
┌─────────────────────────┬───────────┬──────────┬─────────────┬─────────────────┬──────────────┬──────────────┬──────────────┬─────────────────────┬──────────────────┐
│ Time                    ┆ Longitude ┆ Latitude ┆ NR_UE_PCI_0 ┆ NR_UE_Nbr_PCI_1 ┆ NR_UE_RSRP_0 ┆ NR_UE_RSRQ_0 ┆ NR_UE_SINR_0 ┆ NR_UE_Pathloss_DL_0 ┆ NR_UE_Nbr_RSRP_1 │
│ ---                     ┆ ---       ┆ ---      ┆ ---         ┆ ---             ┆ ---          ┆ ---          ┆ ---          ┆ ---                 ┆ ---              │
│ datetime[ms]            ┆ f64       ┆ f64      ┆ i64         ┆ str             ┆ f64          ┆ f64          ┆ f64          ┆ f64                 ┆ str              │
╞═════════════════════════╪═══════════╪══════════╪═════════════╪═════════════════╪══════════════╪══════════════╪══════════════╪═════════════════════╪══════════════════╡
│ 2025-03-14 12:15:01.667 ┆ 29.0283   ┆ 41.10651 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ 93.1                ┆ null             │
│ 2025-03-14 12:15:02.295 ┆ 29.02828  ┆ 41.10649 ┆ 76          ┆ null            ┆ -77.7        ┆ -11.0        ┆ 11.95        ┆ 95.2                ┆ null             │
│ 2025-03-14 12:15:02.666 ┆ 29.02826  ┆ 41.10648 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ 97.0                ┆ null             │
│ 2025-03-14 12:15:03.353 ┆ 29.02823  ┆ 41.10646 ┆ 76          ┆ null            ┆ -81.4        ┆ -11.45       ┆ 9.2          ┆ 97.4                ┆ null             │
│ 2025-03-14 12:15:03.667 ┆ 29.02821  ┆ 41.10644 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ 97.7                ┆ null             │
│ 2025-03-14 12:15:04.368 ┆ 29.02818  ┆ 41.10642 ┆ 76          ┆ null            ┆ -81.25       ┆ -10.85       ┆ 12.75        ┆ 98.35               ┆ null             │
│ 2025-03-14 12:15:05.369 ┆ 29.02813  ┆ 41.10637 ┆ 76          ┆ null            ┆ -83.65       ┆ -10.8        ┆ 15.1         ┆ 97.75               ┆ null             │
│ 2025-03-14 12:15:06.070 ┆ 29.02805  ┆ 41.10632 ┆ 76          ┆ null            ┆ -79.3        ┆ -10.5        ┆ 20.5         ┆ 94.9                ┆ null             │
│ 2025-03-14 12:15:06.549 ┆ 29.02802  ┆ 41.1063  ┆ 76          ┆ null            ┆ -79.1        ┆ -10.5        ┆ 17.3         ┆ 99.5                ┆ null             │
│ 2025-03-14 12:15:07.153 ┆ 29.02798  ┆ 41.10627 ┆ 76          ┆ null            ┆ -84.3        ┆ -10.7        ┆ 17.3         ┆ 97.6                ┆ null             │
│ 2025-03-14 12:15:07.553 ┆ 29.02795  ┆ 41.10625 ┆ 76          ┆ null            ┆ -82.2        ┆ -10.5        ┆ 18.6         ┆ 96.7                ┆ null             │
│ 2025-03-14 12:15:08.417 ┆ 29.02792  ┆ 41.10623 ┆ 76          ┆ null            ┆ -78.65       ┆ -10.45       ┆ 24.6         ┆ 93.15               ┆ null             │
│ 2025-03-14 12:15:09.385 ┆ 29.02788  ┆ 41.10619 ┆ 76          ┆ null            ┆ -76.05       ┆ -10.4        ┆ 25.15        ┆ 92.6                ┆ null             │
│ 2025-03-14 12:15:10.071 ┆ 29.02784  ┆ 41.10617 ┆ 76          ┆ null            ┆ -73.0        ┆ -10.3        ┆ 27.0         ┆ 89.4                ┆ null             │
│ 2025-03-14 12:15:10.629 ┆ 29.02782  ┆ 41.10616 ┆ 76          ┆ null            ┆ -71.9        ┆ -10.4        ┆ 26.4         ┆ 90.9                ┆ null             │
│ 2025-03-14 12:15:11.171 ┆ 29.02781  ┆ 41.10614 ┆ 76          ┆ null            ┆ -71.9        ┆ -10.4        ┆ 26.6         ┆ 86.8                ┆ null             │
│ 2025-03-14 12:15:11.565 ┆ 29.02779  ┆ 41.10613 ┆ 76          ┆ null            ┆ -70.2        ┆ -10.4        ┆ 26.4         ┆ null                ┆ null             │
│ 2025-03-14 12:15:12.089 ┆ 29.02778  ┆ 41.10612 ┆ 76          ┆ null            ┆ -71.0        ┆ -10.4        ┆ 24.6         ┆ 88.0                ┆ null             │
│ 2025-03-14 12:15:12.573 ┆ 29.02778  ┆ 41.1061  ┆ 76          ┆ null            ┆ -72.3        ┆ -10.4        ┆ 23.2         ┆ 92.4                ┆ null             │
│ 2025-03-14 12:15:13.402 ┆ 29.02777  ┆ 41.10609 ┆ 76          ┆ null            ┆ -74.2        ┆ -10.4        ┆ 24.8         ┆ 91.1                ┆ null             │
│ 2025-03-14 12:15:14.366 ┆ 29.02777  ┆ 41.10605 ┆ 76          ┆ null            ┆ -76.25       ┆ -10.4        ┆ 18.85        ┆ 94.1                ┆ null             │
│ 2025-03-14 12:15:15.400 ┆ 29.02777  ┆ 41.10601 ┆ 76          ┆ null            ┆ -78.0        ┆ -10.55       ┆ 17.1         ┆ 92.8                ┆ null             │
│ 2025-03-14 12:15:16.147 ┆ 29.02778  ┆ 41.10596 ┆ 76          ┆ null            ┆ -77.5        ┆ -10.6        ┆ 18.9         ┆ 93.9                ┆ null             │
│ 2025-03-14 12:15:16.646 ┆ 29.02779  ┆ 41.10593 ┆ 76          ┆ null            ┆ -79.4        ┆ -10.5        ┆ 17.7         ┆ 95.7                ┆ null             │
│ 2025-03-14 12:15:17.252 ┆ 29.02779  ┆ 41.1059  ┆ 76          ┆ null            ┆ -79.2        ┆ -10.5        ┆ 20.3         ┆ 93.8                ┆ null             │
│ 2025-03-14 12:15:17.586 ┆ 29.0278   ┆ 41.10587 ┆ 76          ┆ null            ┆ -75.4        ┆ -10.4        ┆ 24.3         ┆ 91.1                ┆ null             │
│ 2025-03-14 12:15:18.387 ┆ 29.02781  ┆ 41.10584 ┆ 76          ┆ null            ┆ -73.75       ┆ -10.5        ┆ 25.55        ┆ 86.5                ┆ null             │
│ 2025-03-14 12:15:19.178 ┆ 29.02781  ┆ 41.10577 ┆ 76          ┆ null            ┆ -69.4        ┆ -10.4        ┆ 24.3         ┆ 85.7                ┆ null             │
│ 2025-03-14 12:15:19.592 ┆ 29.02781  ┆ 41.10574 ┆ 76          ┆ null            ┆ -72.9        ┆ -10.6        ┆ 25.1         ┆ 88.0                ┆ null             │
│ 2025-03-14 12:15:20.174 ┆ 29.02781  ┆ 41.10571 ┆ 76          ┆ null            ┆ -69.2        ┆ -10.6        ┆ 20.2         ┆ 88.3                ┆ null             │
│ 2025-03-14 12:15:20.596 ┆ 29.02781  ┆ 41.10567 ┆ 76          ┆ null            ┆ -72.5        ┆ -10.6        ┆ 16.2         ┆ 91.8                ┆ null             │
│ 2025-03-14 12:15:21.226 ┆ 29.0278   ┆ 41.10564 ┆ 76          ┆ null            ┆ -76.7        ┆ -11.4        ┆ 11.7         ┆ 94.0                ┆ null             │
└─────────────────────────┴───────────┴──────────┴─────────────┴─────────────────┴──────────────┴──────────────┴──────────────┴─────────────────────┴──────────────────┘
shape: (30, 10)
┌─────────────────────────┬───────────┬──────────┬─────────────┬─────────────────┬──────────────┬──────────────┬──────────────┬─────────────────────┬──────────────────┐
│ Time                    ┆ Longitude ┆ Latitude ┆ NR_UE_PCI_0 ┆ NR_UE_Nbr_PCI_1 ┆ NR_UE_RSRP_0 ┆ NR_UE_RSRQ_0 ┆ NR_UE_SINR_0 ┆ NR_UE_Pathloss_DL_0 ┆ NR_UE_Nbr_RSRP_1 │
│ ---                     ┆ ---       ┆ ---      ┆ ---         ┆ ---             ┆ ---          ┆ ---          ┆ ---          ┆ ---                 ┆ ---              │
│ datetime[ms]            ┆ f64       ┆ f64      ┆ i64         ┆ str             ┆ f64          ┆ f64          ┆ f64          ┆ f64                 ┆ str              │
╞═════════════════════════╪═══════════╪══════════╪═════════════╪═════════════════╪══════════════╪══════════════╪══════════════╪═════════════════════╪══════════════════╡
│ 2025-03-14 12:20:41.232 ┆ 29.02633  ┆ 41.10522 ┆ 68          ┆ null            ┆ -70.3        ┆ -10.4        ┆ 30.05        ┆ 89.55               ┆ null             │
│ 2025-03-14 12:20:41.726 ┆ 29.0263   ┆ 41.1052  ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:20:42.256 ┆ 29.02627  ┆ 41.1052  ┆ 68          ┆ null            ┆ -72.2        ┆ -10.3        ┆ 26.95        ┆ 89.6                ┆ null             │
│ 2025-03-14 12:20:42.713 ┆ 29.02624  ┆ 41.10518 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:20:43.389 ┆ 29.02621  ┆ 41.10517 ┆ 68          ┆ null            ┆ -74.95       ┆ -10.4        ┆ 25.15        ┆ 97.3                ┆ null             │
│ 2025-03-14 12:20:44.371 ┆ 29.02612  ┆ 41.10516 ┆ 68          ┆ null            ┆ -72.0        ┆ -10.4        ┆ 29.0         ┆ 92.9                ┆ null             │
│ 2025-03-14 12:20:45.245 ┆ 29.02602  ┆ 41.10515 ┆ 68          ┆ null            ┆ -70.0        ┆ -10.4        ┆ 27.4         ┆ 88.25               ┆ null             │
│ 2025-03-14 12:20:45.734 ┆ 29.02597  ┆ 41.10514 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:20:46.378 ┆ 29.02592  ┆ 41.10514 ┆ 68          ┆ null            ┆ -71.85       ┆ -10.4        ┆ 27.7         ┆ 87.7                ┆ null             │
│ 2025-03-14 12:20:47.238 ┆ 29.02582  ┆ 41.10512 ┆ 68          ┆ null            ┆ -71.65       ┆ -10.4        ┆ 26.9         ┆ 87.25               ┆ null             │
│ 2025-03-14 12:20:47.763 ┆ 29.02578  ┆ 41.10511 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:20:48.373 ┆ 29.02573  ┆ 41.10511 ┆ 68          ┆ null            ┆ -74.25       ┆ -10.4        ┆ 25.35        ┆ 91.15               ┆ null             │
│ 2025-03-14 12:20:49.249 ┆ 29.02563  ┆ 41.10509 ┆ 68          ┆ 76              ┆ -75.8        ┆ -10.4        ┆ 27.1         ┆ 99.85               ┆ null             │
│ 2025-03-14 12:20:49.741 ┆ 29.02558  ┆ 41.10508 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:20:50.236 ┆ 29.02553  ┆ 41.10507 ┆ 68          ┆ 76              ┆ -75.6        ┆ -10.4        ┆ 26.7         ┆ 98.65               ┆ null             │
│ 2025-03-14 12:20:50.733 ┆ 29.02547  ┆ 41.10507 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:20:51.362 ┆ 29.02542  ┆ 41.10506 ┆ 68          ┆ null            ┆ -74.9        ┆ -10.4        ┆ 25.0         ┆ 89.7                ┆ null             │
│ 2025-03-14 12:20:52.224 ┆ 29.02531  ┆ 41.10504 ┆ 68          ┆ null            ┆ -74.1        ┆ -10.4        ┆ 22.1         ┆ 90.4                ┆ null             │
│ 2025-03-14 12:20:52.746 ┆ 29.02525  ┆ 41.10504 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:20:53.237 ┆ 29.02519  ┆ 41.10504 ┆ 68          ┆ null            ┆ -77.2        ┆ -10.4        ┆ 22.45        ┆ 93.25               ┆ null             │
│ 2025-03-14 12:20:53.753 ┆ 29.02513  ┆ 41.10503 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:20:54.378 ┆ 29.02507  ┆ 41.10502 ┆ 68          ┆ null            ┆ -77.2        ┆ -10.4        ┆ 23.95        ┆ 91.85               ┆ null             │
│ 2025-03-14 12:20:55.376 ┆ 29.02497  ┆ 41.105   ┆ 68          ┆ null            ┆ -75.95       ┆ -10.4        ┆ 20.3         ┆ 91.85               ┆ null             │
│ 2025-03-14 12:20:56.245 ┆ 29.02486  ┆ 41.10498 ┆ 68          ┆ null            ┆ -79.8        ┆ -10.5        ┆ 15.45        ┆ 95.7                ┆ null             │
│ 2025-03-14 12:20:56.757 ┆ 29.0248   ┆ 41.10498 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:20:57.380 ┆ 29.02475  ┆ 41.10497 ┆ 68          ┆ null            ┆ -81.0        ┆ -10.45       ┆ 17.45        ┆ 95.75               ┆ null             │
│ 2025-03-14 12:20:58.255 ┆ 29.02465  ┆ 41.10496 ┆ 68          ┆ null            ┆ -79.45       ┆ -10.4        ┆ 20.35        ┆ 95.0                ┆ null             │
│ 2025-03-14 12:20:58.761 ┆ 29.02461  ┆ 41.10495 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:20:59.403 ┆ 29.02456  ┆ 41.10495 ┆ 68          ┆ null            ┆ -81.8        ┆ -10.5        ┆ 15.5         ┆ 98.1                ┆ null             │
│ 2025-03-14 12:21:00.398 ┆ 29.02447  ┆ 41.10494 ┆ 68          ┆ null            ┆ -84.2        ┆ -10.55       ┆ 13.3         ┆ 100.9               ┆ null             │
└─────────────────────────┴───────────┴──────────┴─────────────┴─────────────────┴──────────────┴──────────────┴──────────────┴─────────────────────┴──────────────────┘
shape: (30, 10)
┌─────────────────────────┬───────────┬──────────┬─────────────┬─────────────────┬──────────────┬──────────────┬──────────────┬─────────────────────┬──────────────────┐
│ Time                    ┆ Longitude ┆ Latitude ┆ NR_UE_PCI_0 ┆ NR_UE_Nbr_PCI_1 ┆ NR_UE_RSRP_0 ┆ NR_UE_RSRQ_0 ┆ NR_UE_SINR_0 ┆ NR_UE_Pathloss_DL_0 ┆ NR_UE_Nbr_RSRP_1 │
│ ---                     ┆ ---       ┆ ---      ┆ ---         ┆ ---             ┆ ---          ┆ ---          ┆ ---          ┆ ---                 ┆ ---              │
│ datetime[ms]            ┆ f64       ┆ f64      ┆ i64         ┆ str             ┆ f64          ┆ f64          ┆ f64          ┆ f64                 ┆ str              │
╞═════════════════════════╪═══════════╪══════════╪═════════════╪═════════════════╪══════════════╪══════════════╪══════════════╪═════════════════════╪══════════════════╡
│ 2025-03-14 12:24:25.319 ┆ 29.02674  ┆ 41.10787 ┆ 59          ┆ 76              ┆ -83.4        ┆ -10.9        ┆ 11.35        ┆ 103.8               ┆ null             │
│ 2025-03-14 12:24:25.693 ┆ 29.02667  ┆ 41.10786 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:24:26.358 ┆ 29.02661  ┆ 41.10786 ┆ 59          ┆ 76              ┆ -84.8        ┆ -10.85       ┆ 11.0         ┆ 104.9               ┆ null             │
│ 2025-03-14 12:24:27.321 ┆ 29.02648  ┆ 41.10784 ┆ 59          ┆ 76              ┆ -88.35       ┆ -11.2        ┆ 10.8         ┆ 107.35              ┆ null             │
│ 2025-03-14 12:24:27.787 ┆ 29.02641  ┆ 41.10783 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:24:28.322 ┆ 29.02635  ┆ 41.10783 ┆ 59          ┆ 76              ┆ -87.25       ┆ -11.15       ┆ 10.05        ┆ 107.1               ┆ null             │
│ 2025-03-14 12:24:28.999 ┆ 29.02629  ┆ 41.10782 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:24:29.282 ┆ 29.02623  ┆ 41.10782 ┆ 59          ┆ 76              ┆ -87.25       ┆ -11.45       ┆ 6.9          ┆ 109.95              ┆ null             │
│ 2025-03-14 12:24:29.720 ┆ 29.02617  ┆ 41.10781 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:24:30.367 ┆ 29.02611  ┆ 41.10781 ┆ 59          ┆ 76              ┆ -89.1        ┆ -13.6        ┆ 4.25         ┆ 110.4               ┆ null             │
│ 2025-03-14 12:24:31.380 ┆ 29.02599  ┆ 41.1078  ┆ 59          ┆ 76              ┆ -86.6        ┆ -13.1        ┆ 3.15         ┆ 105.05              ┆ null             │
│ 2025-03-14 12:24:32.328 ┆ 29.02586  ┆ 41.1078  ┆ 59          ┆ 76              ┆ -87.85       ┆ -12.65       ┆ 2.3          ┆ 107.35              ┆ null             │
│ 2025-03-14 12:24:32.686 ┆ 29.0258   ┆ 41.1078  ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:24:33.366 ┆ 29.02574  ┆ 41.1078  ┆ 59          ┆ 48              ┆ -90.95       ┆ -12.75       ┆ 1.55         ┆ 111.6               ┆ null             │
│ 2025-03-14 12:24:34.317 ┆ 29.02561  ┆ 41.10781 ┆ 59          ┆ 76              ┆ -90.55       ┆ -13.4        ┆ 2.25         ┆ 109.5               ┆ null             │
│ 2025-03-14 12:24:34.751 ┆ 29.02555  ┆ 41.10781 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:24:35.362 ┆ 29.02549  ┆ 41.10781 ┆ 59          ┆ 76              ┆ -94.2        ┆ -13.6        ┆ 0.1          ┆ 113.9               ┆ null             │
│ 2025-03-14 12:24:35.649 ┆ 29.02543  ┆ 41.10782 ┆ 59          ┆ 76              ┆ -93.0        ┆ -13.5        ┆ 1.2          ┆ 111.6               ┆ null             │
│ 2025-03-14 12:24:36.385 ┆ 29.02536  ┆ 41.10782 ┆ 59          ┆ 76              ┆ -97.3        ┆ -14.15       ┆ 2.1          ┆ 117.65              ┆ null             │
│ 2025-03-14 12:24:37.147 ┆ 29.02523  ┆ 41.10782 ┆ 59          ┆ null            ┆ -98.3        ┆ -16.4        ┆ -0.3         ┆ 121.6               ┆ null             │
│ 2025-03-14 12:24:37.631 ┆ 29.02517  ┆ 41.10783 ┆ 59          ┆ null            ┆ -96.0        ┆ -15.4        ┆ -0.6         ┆ 121.1               ┆ null             │
│ 2025-03-14 12:24:38.219 ┆ 29.02511  ┆ 41.10783 ┆ 30          ┆ null            ┆ -89.75       ┆ -12.85       ┆ -6.25        ┆ 122.8               ┆ null             │
│ 2025-03-14 12:24:38.684 ┆ 29.02504  ┆ 41.10784 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ 121.2               ┆ null             │
│ 2025-03-14 12:24:39.444 ┆ 29.02497  ┆ 41.10785 ┆ 30          ┆ null            ┆ -85.6        ┆ -10.65       ┆ 16.9         ┆ 105.25              ┆ null             │
│ 2025-03-14 12:24:40.418 ┆ 29.02484  ┆ 41.10786 ┆ 30          ┆ null            ┆ -77.9        ┆ -10.4        ┆ 26.05        ┆ 95.4                ┆ null             │
│ 2025-03-14 12:24:41.226 ┆ 29.02473  ┆ 41.10787 ┆ 30          ┆ null            ┆ -73.4        ┆ -10.4        ┆ 30.4         ┆ 92.2                ┆ null             │
│ 2025-03-14 12:24:41.645 ┆ 29.02467  ┆ 41.10787 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ 93.5                ┆ null             │
│ 2025-03-14 12:24:43.342 ┆ 29.02451  ┆ 41.10786 ┆ 30          ┆ null            ┆ -74.4        ┆ -10.4        ┆ 29.45        ┆ 94.3                ┆ null             │
│ 2025-03-14 12:24:44.131 ┆ 29.02439  ┆ 41.10784 ┆ 30          ┆ null            ┆ -77.4        ┆ -10.45       ┆ 27.2         ┆ 97.7                ┆ null             │
│ 2025-03-14 12:24:44.654 ┆ 29.02433  ┆ 41.10783 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ 96.8                ┆ null             │
└─────────────────────────┴───────────┴──────────┴─────────────┴─────────────────┴──────────────┴──────────────┴──────────────┴─────────────────────┴──────────────────┘
shape: (33, 10)
┌─────────────────────────┬───────────┬──────────┬─────────────┬─────────────────┬──────────────┬──────────────┬──────────────┬─────────────────────┬──────────────────┐
│ Time                    ┆ Longitude ┆ Latitude ┆ NR_UE_PCI_0 ┆ NR_UE_Nbr_PCI_1 ┆ NR_UE_RSRP_0 ┆ NR_UE_RSRQ_0 ┆ NR_UE_SINR_0 ┆ NR_UE_Pathloss_DL_0 ┆ NR_UE_Nbr_RSRP_1 │
│ ---                     ┆ ---       ┆ ---      ┆ ---         ┆ ---             ┆ ---          ┆ ---          ┆ ---          ┆ ---                 ┆ ---              │
│ datetime[ms]            ┆ f64       ┆ f64      ┆ i64         ┆ str             ┆ f64          ┆ f64          ┆ f64          ┆ f64                 ┆ str              │
╞═════════════════════════╪═══════════╪══════════╪═════════════╪═════════════════╪══════════════╪══════════════╪══════════════╪═════════════════════╪══════════════════╡
│ 2025-03-14 12:31:29.500 ┆ 29.02566  ┆ 41.0989  ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │
│ 2025-03-14 12:31:30.002 ┆ 29.02557  ┆ 41.09889 ┆ null        ┆ null            ┆ null         ┆ null         ┆ null         ┆ null                ┆ null             │

In [112]:


target_time = pl.datetime(2025, 3, 14, 12, 24, 34, 751000)

oncesi = target_time - timedelta(seconds=10)
sonrasi = target_time + timedelta(seconds=10)

context_data = df.filter(
    (pl.col("Time") >= oncesi) & 
    (pl.col("Time") <= sonrasi)
).sort("Time")

print(context_data)

shape: (30, 53)
┌───────────┬──────────┬──────────────┬──────────────┬──────────────┬──────────────────┬──────────────────┬──────────────────┬──────────────────┬──────────────────┬──────────────────┬──────────────────┬──────────────────┬──────────────────┬──────────────────┬─────────────────────┬──────────────────────┬──────────────────────────┬───────────────────┬─────────────────────────┬────────────────────────────┬───────────────┬─────────────────────────┬───────────────────────────┬────────────────────┬──────────────────────────┬───────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬───────────────┬───────────────────────┬────────────────────────────┬─────────────────────────────┬─────────────────────────────────┬────────────────────────────┬────────────────────────┬─────────────────────────────────┬────────────────────┬───────────────────┬────────────────────────┬──────────────────────┬─────────────────┬────────────────────────┬─────────────┬────────────────────────┬─────────────────┬────────────────────────┬──────────────────────┬────────────────────────────┬────────────────────┐
│ Longitude ┆ Latitude ┆ NR_UE_RSRP_0 ┆ NR_UE_RSRQ_0 ┆ NR_UE_SINR_0 ┆ NR_UE_Nbr_RSRP_0 ┆ NR_UE_Nbr_RSRP_1 ┆ NR_UE_Nbr_RSRP_2 ┆ NR_UE_Nbr_RSRP_3 ┆ NR_UE_Nbr_RSRP_4 ┆ NR_UE_Nbr_RSRQ_0 ┆ NR_UE_Nbr_RSRQ_1 ┆ NR_UE_Nbr_RSRQ_2 ┆ NR_UE_Nbr_RSRQ_3 ┆ NR_UE_Nbr_RSRQ_4 ┆ NR_UE_Pathloss_DL_0 ┆ NR_UE_Timing_Advance ┆ NR_UE_Throughput_PDCP_DL ┆ App_Throughput_DL ┆ Time                    ┆ NR_UE_CCE_AggregationLev_0 ┆ NR_UE_RI_DL_0 ┆ NR_UE_RRCConnectionDrop ┆ NR_UE_Modulation_Avg_DL_0 ┆ NR_UE_RRCReEstFail ┆ NR_UE_RRCReEst_EndResult ┆ NR_UE_RRCHOOK ┆ NR_UE_Nbr_PCI_0 ┆ NR_UE_Nbr_PCI_2 ┆ NR_UE_RACH_Fail ┆ NR_UE_Nbr_PCI_3 ┆ NR_UE_BLER_DL_0 ┆ NR_UE_RACH_OK ┆ NR_UE_RRCReEstAttempt ┆ NR_UE_RRCConnectionSetupOk ┆ NR_UE_RRCConnectionComplete ┆ NR_UE_MCS_DL_0                  ┆ NR_UE_RACH_Procedure_Count ┆ NR_UE_Power_Tx_PRACH_0 ┆ NR_RRC_MsgType                  ┆ NR_UE_RRCHOAttempt ┆ NR_UE_RB_Num_DL_0 ┆ NR_UE_Power_Tx_PUSCH_0 ┆ NR_UE_NACK_Rate_UL_0 ┆ NR_UE_Nbr_PCI_4 ┆ NAS_5GS_MM_MessageType ┆ NR_UE_PCI_0 ┆ NAS_5GS_SM_MessageType ┆ NR_UE_Nbr_PCI_1 ┆ NR_UE_Ack_As_Nack_DL_0 ┆ NR_UE_NACK_Rate_DL_0 ┆ NR_UE_RRCConnectionAttempt ┆ NR_UE_RACH_Attempt │
│ ---       ┆ ---      ┆ ---          ┆ ---          ┆ ---          ┆ ---              ┆ ---              ┆ ---              ┆ ---              ┆ ---              ┆ ---              ┆ ---              ┆ ---              ┆ ---              ┆ ---              ┆ ---                 ┆ ---                  ┆ ---                      ┆ ---               ┆ ---                     ┆ ---                        ┆ ---           ┆ ---                     ┆ ---                       ┆ ---                ┆ ---                      ┆ ---           ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---           ┆ ---                   ┆ ---                        ┆ ---                         ┆ ---                             ┆ ---                        ┆ ---                    ┆ ---                             ┆ ---                ┆ ---               ┆ ---                    ┆ ---                  ┆ ---             ┆ ---                    ┆ ---         ┆ ---                    ┆ ---             ┆ ---                    ┆ ---                  ┆ ---                        ┆ ---                │
│ f64       ┆ f64      ┆ f64          ┆ f64          ┆ f64          ┆ f64              ┆ str              ┆ str              ┆ str              ┆ str              ┆ f64              ┆ str              ┆ str              ┆ str              ┆ str              ┆ f64                 ┆ str                  ┆ f64                      ┆ str               ┆ datetime[ms]            ┆ str                        ┆ str           ┆ i64                     ┆ str                       ┆ i64                ┆ str                      ┆ i64           ┆ i64             ┆ str             ┆ i64             ┆ str             ┆ str             ┆ i64           ┆ i64                   ┆ i64                        ┆ i64                         ┆ str                             ┆ str                        ┆ str                    ┆ str                             ┆ i64                ┆ str               ┆ f64                    ┆ f64                  ┆ str             ┆ str                    ┆ i64         ┆ str                    ┆ str             ┆ str                    ┆ str                  ┆ i64                        ┆ i64                │
╞═══════════╪══════════╪══════════════╪══════════════╪══════════════╪══════════════════╪══════════════════╪══════════════════╪══════════════════╪══════════════════╪══════════════════╪══════════════════╪══════════════════╪══════════════════╪══════════════════╪═════════════════════╪══════════════════════╪══════════════════════════╪═══════════════════╪═════════════════════════╪════════════════════════════╪═══════════════╪═════════════════════════╪═══════════════════════════╪════════════════════╪══════════════════════════╪═══════════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╪═══════════════╪═══════════════════════╪════════════════════════════╪═════════════════════════════╪═════════════════════════════════╪════════════════════════════╪════════════════════════╪═════════════════════════════════╪════════════════════╪═══════════════════╪════════════════════════╪══════════════════════╪═════════════════╪════════════════════════╪═════════════╪════════════════════════╪═════════════════╪════════════════════════╪══════════════════════╪════════════════════════════╪════════════════════╡
│ 29.02674  ┆ 41.10787 ┆ -83.4        ┆ -10.9        ┆ 11.35        ┆ -96.6            ┆ null             ┆ null             ┆ null             ┆ null             ┆ -21.5            ┆ null             ┆ null             ┆ null             ┆ null             ┆ 103.8               ┆ null                 ┆ 96071.68                 ┆ null              ┆ 2025-03-14 12:24:25.319 ┆ LEVEL_1                    ┆ Rank4         ┆ 0                       ┆ 256QAM                    ┆ 0                  ┆ null                     ┆ 0             ┆ 48              ┆ null            ┆ 0               ┆ null            ┆ 5.7             ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 27 (64QAM OR 256QAM / Low SE -… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 66                ┆ 17.5                   ┆ 0.0                  ┆ null            ┆ null                   ┆ 59          ┆ null                   ┆ 76              ┆ 0                      ┆ 5.7                  ┆ 0                          ┆ 0                  │
│ 29.02667  ┆ 41.10786 ┆ null         ┆ null         ┆ null         ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null                ┆ null                 ┆ null                     ┆ null              ┆ 2025-03-14 12:24:25.693 ┆ LEVEL_1                    ┆ Rank3         ┆ 0                       ┆ 256QAM                    ┆ 0                  ┆ null                     ┆ 0             ┆ null            ┆ null            ┆ 0               ┆ null            ┆ 7.6             ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 27 (64QAM OR 256QAM / Low SE -… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 74                ┆ null                   ┆ null                 ┆ null            ┆ null                   ┆ null        ┆ null                   ┆ null            ┆ 0                      ┆ 7.6                  ┆ 0                          ┆ 0                  │
│ 29.02661  ┆ 41.10786 ┆ -84.8        ┆ -10.85       ┆ 11.0         ┆ -97.15           ┆ null             ┆ null             ┆ null             ┆ null             ┆ -21.0            ┆ null             ┆ null             ┆ null             ┆ null             ┆ 104.9               ┆ null                 ┆ 95966.77                 ┆ null              ┆ 2025-03-14 12:24:26.358 ┆ LEVEL_1                    ┆ Rank3         ┆ 0                       ┆ 256QAM                    ┆ 0                  ┆ null                     ┆ 0             ┆ 48              ┆ null            ┆ 0               ┆ null            ┆ 5.3             ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 27 (64QAM OR 256QAM / Low SE -… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 76                ┆ 17.5                   ┆ 1.2                  ┆ null            ┆ null                   ┆ 59          ┆ null                   ┆ 76              ┆ 0                      ┆ 5.3                  ┆ 0                          ┆ 0                  │
│ 29.02648  ┆ 41.10784 ┆ -88.35       ┆ -11.2        ┆ 10.8         ┆ -104.6           ┆ null             ┆ null             ┆ null             ┆ null             ┆ -21.8            ┆ null             ┆ null             ┆ null             ┆ null             ┆ 107.35              ┆ null                 ┆ 95936.065                ┆ null              ┆ 2025-03-14 12:24:27.321 ┆ LEVEL_2                    ┆ Rank3         ┆ 0                       ┆ 256QAM                    ┆ 0                  ┆ null                     ┆ 0             ┆ 48              ┆ null            ┆ 0               ┆ null            ┆ 2.8             ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 27 (64QAM OR 256QAM / Low SE -… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 82                ┆ 17.5                   ┆ 0.0                  ┆ null            ┆ null                   ┆ 59          ┆ null                   ┆ 76              ┆ 0                      ┆ 2.8                  ┆ 0                          ┆ 0                  │
│ 29.02641  ┆ 41.10783 ┆ null         ┆ null         ┆ null         ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null                ┆ null                 ┆ null                     ┆ null              ┆ 2025-03-14 12:24:27.787 ┆ LEVEL_2                    ┆ Rank3         ┆ 0                       ┆ 256QAM                    ┆ 0                  ┆ null                     ┆ 0             ┆ null            ┆ null            ┆ 0               ┆ null            ┆ 13.2            ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 27 (64QAM OR 256QAM / Low SE -… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 81                ┆ null                   ┆ null                 ┆ null            ┆ null                   ┆ null        ┆ null                   ┆ null            ┆ 0                      ┆ 13.2                 ┆ 0                          ┆ 0                  │
│ 29.02635  ┆ 41.10783 ┆ -87.25       ┆ -11.15       ┆ 10.05        ┆ -94.15           ┆ null             ┆ null             ┆ null             ┆ null             ┆ -16.5            ┆ null             ┆ null             ┆ null             ┆ null             ┆ 107.1               ┆ null                 ┆ 96025.49                 ┆ null              ┆ 2025-03-14 12:24:28.322 ┆ LEVEL_2                    ┆ Rank3         ┆ 0                       ┆ 256QAM                    ┆ 0                  ┆ null                     ┆ 0             ┆ 30              ┆ null            ┆ 0               ┆ null            ┆ 2               ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 27 (64QAM OR 256QAM / Low SE -… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 101               ┆ 17.5                   ┆ 0.0                  ┆ null            ┆ null                   ┆ 59          ┆ null                   ┆ 76              ┆ 0                      ┆ 2                    ┆ 0                          ┆ 0                  │
│ 29.02629  ┆ 41.10782 ┆ null         ┆ null         ┆ null         ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null                ┆ null                 ┆ null                     ┆ null              ┆ 2025-03-14 12:24:28.999 ┆ null                       ┆ null          ┆ 0                       ┆ null                      ┆ 0                  ┆ null                     ┆ 0             ┆ null            ┆ null            ┆ 0               ┆ null            ┆ null            ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ null                            ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ null              ┆ null                   ┆ null                 ┆ null            ┆ null                   ┆ null        ┆ null                   ┆ null            ┆ null                   ┆ null                 ┆ 0                          ┆ 0                  │
│ 29.02623  ┆ 41.10782 ┆ -87.25       ┆ -11.45       ┆ 6.9          ┆ -93.45           ┆ null             ┆ null             ┆ null             ┆ null             ┆ -17.6            ┆ null             ┆ null             ┆ null             ┆ null             ┆ 109.95              ┆ null                 ┆ 96328.0                  ┆ null              ┆ 2025-03-14 12:24:29.282 ┆ LEVEL_1                    ┆ Rank2         ┆ 0                       ┆ 256QAM                    ┆ 0                  ┆ null                     ┆ 0             ┆ 30              ┆ null            ┆ 0               ┆ null            ┆ 1               ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 27 (64QAM OR 256QAM / Low SE -… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 103               ┆ 17.5                   ┆ 0.0                  ┆ null            ┆ null                   ┆ 59          ┆ null                   ┆ 76              ┆ 0                      ┆ 1                    ┆ 0                          ┆ 0                  │
│ 29.02617  ┆ 41.10781 ┆ null         ┆ null         ┆ null         ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null             ┆ null                ┆ null                 ┆ null                     ┆ null              ┆ 2025-03-14 12:24:29.720 ┆ LEVEL_1                    ┆ Rank2         ┆ 0                       ┆ 256QAM                    ┆ 0                  ┆ null                     ┆ 0             ┆ null            ┆ null            ┆ 0               ┆ null            ┆ 3.7             ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 27 (64QAM OR 256QAM / Low SE -… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 103               ┆ null                   ┆ null                 ┆ null            ┆ null                   ┆ null        ┆ null                   ┆ null            ┆ 0                      ┆ 3.7                  ┆ 0                          ┆ 0                  │
│ 29.02611  ┆ 41.10781 ┆ -89.1        ┆ -13.6        ┆ 4.25         ┆ -94.9            ┆ null             ┆ null             ┆ null             ┆ null             ┆ -18.25           ┆ null             ┆ null             ┆ null             ┆ null             ┆ 110.4               ┆ null                 ┆ 96061.44                 ┆ null              ┆ 2025-03-14 12:24:30.367 ┆ LEVEL_2                    ┆ Rank2         ┆ 0                       ┆ 256QAM                    ┆ 0                  ┆ null                     ┆ 0             ┆ 30              ┆ 76              ┆ 0               ┆ null            ┆ 1.7             ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 27 (64QAM OR 256QAM / Low SE -… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 105               ┆ 17.5                   ┆ 0.0                  ┆ null            ┆ null                   ┆ 59          ┆ null                   ┆ 76              ┆ 0                      ┆ 1.7                  ┆ 0                          ┆ 0                  │
│ 29.02599  ┆ 41.1078  ┆ -86.6        ┆ -13.1        ┆ 3.15         ┆ -93.65           ┆ null             ┆ null             ┆ null             ┆ null             ┆ -17.9            ┆ null             ┆ null             ┆ null             ┆ null             ┆ 105.05              ┆ null                 ┆ 96491.52                 ┆ null              ┆ 2025-03-14 12:24:31.380 ┆ LEVEL_1                    ┆ Rank4         ┆ 0                       ┆ 64QAM                     ┆ 0                  ┆ null                     ┆ 0             ┆ 30              ┆ null            ┆ 0               ┆ null            ┆ 17.8            ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 17 (64QAM OR 256QAM / Low SE -… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 117               ┆ 17.5                   ┆ 3.0                  ┆ null            ┆ null                   ┆ 59          ┆ null                   ┆ 76              ┆ 0                      ┆ 17.8                 ┆ 0                          ┆ 0                  │
│ 29.02586  ┆ 41.1078  ┆ -87.85       ┆ -12.65       ┆ 2.3          ┆ -93.4            ┆ null             ┆ null             ┆ null             ┆ null             ┆ -16.5            ┆ null             ┆ null             ┆ null             ┆ null             ┆ 107.35              ┆ null                 ┆ 96368.64                 ┆ null              ┆ 2025-03-14 12:24:32.328 ┆ LEVEL_1                    ┆ Rank4         ┆ 0                       ┆ 64QAM                     ┆ 0                  ┆ null                     ┆ 0             ┆ 30              ┆ null            ┆ 0               ┆ null            ┆ 13.1            ┆ 0             ┆ 0                     ┆ 0                          ┆ 0                           ┆ 15 (16QAM OR 64QAM OR 256QAM /… ┆ null                       ┆ null                   ┆ null                            ┆ 0                  ┆ 131               ┆ 17.5                   ┆ 1.0                  ┆ null            ┆ null                   ┆ 59          ┆ null                   ┆ 76              ┆ 0                      ┆ 13.1                 ┆ 0                          ┆ 0                  │

In [92]:
context_data

shape: (4, 53)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Longitude ┆ Latitude ┆ NR_UE_RSR ┆ NR_UE_RSR ┆ … ┆ NR_UE_Ack ┆ NR_UE_NAC ┆ NR_UE_RRC ┆ NR_UE_RAC │
│ ---       ┆ ---      ┆ P_0       ┆ Q_0       ┆   ┆ _As_Nack_ ┆ K_Rate_DL ┆ Connectio ┆ H_Attempt │
│ f64       ┆ f64      ┆ ---       ┆ ---       ┆   ┆ DL_0      ┆ _0        ┆ nAttempt  ┆ ---       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i64       │
│           ┆          ┆           ┆           ┆   ┆ str       ┆ str       ┆ i64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 29.02561  ┆ 41.10781 ┆ -90.55    ┆ -13.4     ┆ … ┆ 0         ┆ 8.8       ┆ 0         ┆ 0         │
│ 29.02555  ┆ 41.10781 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 8.2       ┆ 0         ┆ 0         │
│ 29.02549  ┆ 41.10781 ┆ -94.2     ┆ -13.6     ┆ … ┆ 0         ┆ 4         ┆ 0         ┆ 0         │
│ 29.02543  ┆ 41.10782 ┆ -93.0     ┆ -13.5     ┆ … ┆ 0         ┆ 6.9       ┆ 0         ┆ 0         │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘