In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from path_config import PathConfig
paths = PathConfig()

In [2]:
grouped_dl = pd.read_csv(paths._processed_saha_olcum_dir / 'grouped_dl.csv')
grouped_ul = pd.read_csv(paths._processed_saha_olcum_dir / 'grouped_ul.csv')

In [3]:
bs_data = pd.read_excel(paths.Hucre_Bilgileri)

In [4]:
pcis = bs_data["PCI "].tolist()

In [5]:
encoding_dl = pd.DataFrame()

In [6]:
pcis

[30, 40, 59, 48, 68, 76, 3, 13, 23]

In [7]:
grouped_dl

,Time,NR_UE_Ack_As_Nack_DL_0,NR_UE_Nbr_RSRP_4,NR_UE_Timing_Advance,NR_UE_Nbr_RSRP_3,NR_UE_RACH_Procedure_Count,NR_UE_Nbr_RSRP_1,NR_UE_NACK_Rate_UL_0,NR_UE_RB_Num_DL_0,NR_UE_Nbr_RSRQ_2,...,NR_UE_Nbr_PCI_3,NR_UE_PCI_0,NR_RRC_MsgType,NR_UE_Nbr_PCI_2,NR_UE_Nbr_PCI_1,NR_UE_RRCReEst_EndResult,NR_UE_MCS_DL_0,NAS_5GS_SM_MessageType,Longitude,Latitude
0,2025-03-14 12:14:33.444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.02949,41.10723
1,2025-03-14 12:14:34.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.02949,41.10723
2,2025-03-14 12:14:34.013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.02949,41.10723
3,2025-03-14 12:14:34.016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.02949,41.10723
4,2025-03-14 12:14:34.030,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,48.0,NaN,NaN,NaN,NaN,NaN,NaN,29.02949,41.10723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5776,2025-03-14 12:32:17.647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.02143,41.10031
5777,2025-03-14 12:32:17.649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.02143,41.10031
5778,2025-03-14 12:32:17.650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.02143,41.10031
5779,2025-03-14 12:32:17.781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.02143,41.10031
5780,2025-03-14 12:32:17.785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.02143,41.10031

In [8]:
[print(col, "\n", grouped_dl[col].unique(), end= f"\n{'-'*50}\n") for col in grouped_dl.columns 
 if 'PCI' not in col and 'RSRP' not in col and 'RSRQ' not in col and 'SINR' 
 not in col and grouped_dl[col].dtype != 'bool' and grouped_dl[col].nunique() < 50]

NR_UE_Timing_Advance
 [nan  4.  1.  3.  2.  8.  5.  0.  7. 16. 13. 25. 20. 35. 17. 30. 11. 36.
 10.  9. 22. 26.]
--------------------------------------------------
NR_UE_RACH_Procedure_Count
 [ nan  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
 14.  15.5 17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
 29.  30.  31.  32.  33.  34.  35.  36.  37.5 39.  40.  41. ]
--------------------------------------------------
NR_UE_Power_Tx_PRACH_0
 [  nan -14.  -26.   -2.  -28.   14.  -12.   -7.    2.    6.    0.    1.
  -6.   20.  -18.5  -1.  -20.  -11.   -8.  -17.   22.   27.   30.   23.
  27.5]
--------------------------------------------------
NR_UE_CCE_AggregationLev_0
 [nan 'LEVEL_2' 'LEVEL_1' 'LEVEL_16' 'LEVEL_4' 'LEVEL_8']
--------------------------------------------------
NR_UE_Modulation_Avg_DL_0
 [nan '256QAM' '64QAM' '16QAM' 'QPSK']
--------------------------------------------------
NAS_5GS_MM_MessageType
 [nan 'Registration request' 'Registration accept' 'Registration reject'
 'Authentication request' 'Configuration update command'
 'UL NAS transport' 'DL NAS transport']
--------------------------------------------------
NR_UE_RI_DL_0
 [nan 'Rank2' 'Rank3' 'Rank4' 'Rank1']
--------------------------------------------------
NR_RRC_MsgType
 [nan ' BCCH-BCH MIB' ' BCCH-DL_SCH SIB2' ' DL-DCCH RRCReconfiguration'
 ' UL-DCCH MeasurementReport' ' BCCH-DL_SCH SIB1'
 ' UL-DCCH RRCReconfigurationComplete' ' DL-DCCH SecurityModeCommand'
 ' DL-DCCH DLInformationTransfer' ' UL-CCCH RRCSetupRequest'
 ' UL-DCCH ULInformationTransfer' ' DL-CCCH RRCSetup'
 ' UL-DCCH RRCSetupComplete' ' UL-DCCH SecurityModeComplete']
--------------------------------------------------
NR_UE_RRCReEst_EndResult
 [nan 'Re-establishment failure after Request']
--------------------------------------------------
NR_UE_MCS_DL_0
 [nan '27 (64QAM OR 256QAM / Low SE -64QAM)'
 '21 (64QAM OR 256QAM / Low SE -16QAM)'
 '25 (64QAM OR 256QAM OR 1024 QAM / Low SE -64QAM)'
 '26 (64QAM OR 256QAM OR 1024 QAM / Low SE -64QAM)'
 '24 (64QAM OR 256QAM OR 1024 QAM / Low SE -64QAM)'
 '23 (64QAM OR 256QAM OR 1024 QAM / Low SE -64QAM)'
 '20 (64QAM OR 256QAM / Low SE -16QAM)'
 '22 (64QAM OR 256QAM / Low SE -16QAM)'
 '13 (16QAM OR 64QAM / Low SE -QPSK)' '14 (16QAM OR 64QAM / Low SE -QPSK)'
 '16 (16QAM OR 64QAM OR 256QAM / Low SE -16QAM)'
 '12 (16QAM OR 64QAM / Low SE -QPSK)' '10 (16QAM OR 64QAM / Low SE -QPSK)'
 '9 (QPSK OR 16QAM OR 64QAM / Low SE -QPSK)'
 '17 (64QAM OR 256QAM / Low SE -16QAM)'
 '15 (16QAM OR 64QAM OR 256QAM / Low SE -16QAM)'
 '18 (64QAM OR 256QAM / Low SE -16QAM)'
 '19 (64QAM OR 256QAM / Low SE -16QAM)' '28 (64QAM / Low SE -64QAM)'
 '0 (QPSK)' '1 (QPSK)' '11 (16QAM OR 64QAM / Low SE -QPSK)'
 '8 (QPSK OR 16QAM OR 64QAM / Low SE -QPSK)'
 '6 (QPSK OR 16QAM OR 64QAM / Low SE -QPSK)'
 '7 (QPSK OR 16QAM OR 64QAM / Low SE -QPSK)'
 '5 (QPSK OR 16QAM / Low SE -QPSK)' '4 (QPSK OR 16QAM / Low SE -QPSK)'
 '3 (QPSK OR 16QAM / Low SE -QPSK)' '2 (QPSK)']
--------------------------------------------------
NAS_5GS_SM_MessageType
 [nan 'PDU session establishment request'
 'PDU session establishment accept']
--------------------------------------------------

[None, None, None, None, None, None, None, None, None, None, None]

In [9]:
encoding_dl[["Time", "Latitude", "Longitude"]] = grouped_dl[["Time", "Latitude", "Longitude"]]

In LTE networks, the reporting range for RSRP is typically between -140 dBm and -44 dBm, with a resolution of 1 dB.<br>
For 5G New Radio (NR), the ranges differ, with Synchronization Signal RSRP (SS-RSRP) spanning from -30 dBm to -156 dBm and <br>
Channel State Information RSRP (CSI-RSRP) ranging from -45 dBm to -139 dBm. <br>
<br>
The typical reporting range for RSRQ in LTE is from -19.5 dB to -3 dB. <br>
In contrast, 5G NR employs a wider range for RSRQ, spanning from -43 dB to 20 dB for both SS-RSRQ and CSI-RSRQ. <br>
<br>
 It is worth noting that a minimum SINR of -20 dB is often required for the user equipment to reliably detect RSRP and RSRQ. <br>
 For 5G NR, SINR values for SS-SINR and CSI-SINR typically range from -23 dB to 40 dB , <br>
 and these values are often reported as a coded index from 0 to 127.

In [10]:
encoding_dl[[f"RSRP_{pci}" for pci in pcis]] = np.nan
encoding_dl[[f"RSRQ_{pci}" for pci in pcis]] = np.nan
encoding_dl[[f"SINR_{pci}" for pci in pcis]] = np.nan

In [11]:
def encode_dl(row):
    if row["NR_UE_PCI_0"] in pcis:
        encoding_dl.at[row.name, f"RSRP_{int(row['NR_UE_PCI_0'])}"] = row["NR_UE_RSRP_0"]
        encoding_dl.at[row.name, f"RSRQ_{int(row['NR_UE_PCI_0'])}"] = row["NR_UE_RSRQ_0"]
        encoding_dl.at[row.name, f"SINR_{int(row['NR_UE_PCI_0'])}"] = row["NR_UE_SINR_0"]
    for i in range(4):
        if row[f"NR_UE_Nbr_PCI_{i}"] in pcis:
            encoding_dl.at[row.name, f"RSRP_{int(row[f'NR_UE_Nbr_PCI_{i}'])}"] = row[f"NR_UE_Nbr_RSRP_{i}"]
            encoding_dl.at[row.name, f"RSRQ_{int(row[f'NR_UE_Nbr_PCI_{i}'])}"] = row[f"NR_UE_Nbr_RSRQ_{i}"]
    
    
grouped_dl.apply(encode_dl, axis=1)

0       None
1       None
2       None
3       None
4       None
        ...
5776    None
5777    None
5778    None
5779    None
5780    None
Length: 5781, dtype: object

In [12]:
encoding_dl

,Time,Latitude,Longitude,RSRP_30,RSRP_40,RSRP_59,RSRP_48,RSRP_68,RSRP_76,RSRP_3,...,RSRQ_23,SINR_30,SINR_40,SINR_59,SINR_48,SINR_68,SINR_76,SINR_3,SINR_13,SINR_23
0,2025-03-14 12:14:33.444,41.10723,29.02949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-03-14 12:14:34.000,41.10723,29.02949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-03-14 12:14:34.013,41.10723,29.02949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-03-14 12:14:34.016,41.10723,29.02949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-03-14 12:14:34.030,41.10723,29.02949,NaN,NaN,NaN,-84.4,NaN,-96.9,NaN,...,NaN,NaN,NaN,NaN,6.9,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5776,2025-03-14 12:32:17.647,41.10031,29.02143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5777,2025-03-14 12:32:17.649,41.10031,29.02143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5778,2025-03-14 12:32:17.650,41.10031,29.02143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5779,2025-03-14 12:32:17.781,41.10031,29.02143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5780,2025-03-14 12:32:17.785,41.10031,29.02143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN