In [25]:
import pandas as pd
import numpy as np

In [26]:
dl = pd.read_excel("5G_DL.xlsx",sheet_name="Series Formatted Data")
dl = dl.drop(["Technology_Mode","Unnamed: 48"],axis=1)

In [27]:
dl["Time"] = dl["Time"].dt.floor('s')

In [28]:
new_dl = pd.DataFrame()

mean_cols = [
             "NR_UE_RSRP_0",
             "NR_UE_RSRQ_0",
             "NR_UE_SINR_0",	
             "NR_UE_Nbr_RSRP_0",	
             "NR_UE_Nbr_RSRP_1",
             "NR_UE_Nbr_RSRP_2",
             "NR_UE_Nbr_RSRP_3",
             "NR_UE_Nbr_RSRP_4",
             "NR_UE_Nbr_RSRQ_0",
             "NR_UE_Nbr_RSRQ_1",
             "NR_UE_Nbr_RSRQ_2",
             "NR_UE_Nbr_RSRQ_3",
             "NR_UE_Nbr_RSRQ_4"]

last_known_data_cols = [
                        "NR_UE_PCI_0",
                        "NR_UE_Nbr_PCI_0",
                        "NR_UE_Nbr_PCI_1",	
                        "NR_UE_Nbr_PCI_2",	
                        "NR_UE_Nbr_PCI_3",	
                        "NR_UE_Nbr_PCI_4",
                        ]

for row in dl['Time'].unique():

    filtered_row_mean = dl[dl["Time"] == row][mean_cols].mean()
    filtered_row_last = dl[dl["Time"] == row][last_known_data_cols]
    last_known_values = filtered_row_last.apply(lambda x: x.dropna().iloc[-1] if not x.dropna().empty else np.nan)
    filtered_row = pd.concat([pd.Series({'Time': row}), filtered_row_mean, last_known_values])
    new_dl = pd.concat([new_dl, filtered_row.to_frame().T], ignore_index=True)
             
new_dl

,Time,NR_UE_RSRP_0,NR_UE_RSRQ_0,NR_UE_SINR_0,NR_UE_Nbr_RSRP_0,NR_UE_Nbr_RSRP_1,NR_UE_Nbr_RSRP_2,NR_UE_Nbr_RSRP_3,NR_UE_Nbr_RSRP_4,NR_UE_Nbr_RSRQ_0,NR_UE_Nbr_RSRQ_1,NR_UE_Nbr_RSRQ_2,NR_UE_Nbr_RSRQ_3,NR_UE_Nbr_RSRQ_4,NR_UE_PCI_0,NR_UE_Nbr_PCI_0,NR_UE_Nbr_PCI_1,NR_UE_Nbr_PCI_2,NR_UE_Nbr_PCI_3,NR_UE_Nbr_PCI_4
0,2025-03-14 12:14:33,-87.1,-11.2,7.3,-97.3,NaN,NaN,NaN,NaN,-16.3,NaN,NaN,NaN,NaN,48.0,76.0,NaN,NaN,NaN,NaN
1,2025-03-14 12:14:34,-85.233333,-11.233333,6.25,-96.266667,NaN,NaN,NaN,NaN,-16.6,NaN,NaN,NaN,NaN,48.0,76.0,NaN,NaN,NaN,NaN
2,2025-03-14 12:14:35,-86.25,-11.1,11.65,-98.25,NaN,NaN,NaN,NaN,-17.05,NaN,NaN,NaN,NaN,48.0,76.0,NaN,NaN,NaN,NaN
3,2025-03-14 12:14:36,-87.6,-10.55,11.6,-99.4,NaN,NaN,NaN,NaN,-16.85,NaN,NaN,NaN,NaN,48.0,76.0,NaN,NaN,NaN,NaN
4,2025-03-14 12:14:37,-86.65,-10.6,11.7,-96.85,NaN,NaN,NaN,NaN,-13.25,NaN,NaN,NaN,NaN,48.0,76.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,2025-03-14 12:32:13,-118.6,-13.2,2.45,-122.85,NaN,NaN,NaN,NaN,-16.95,NaN,NaN,NaN,NaN,68.0,59.0,NaN,NaN,NaN,NaN
1061,2025-03-14 12:32:14,-118.2,-13.55,2.4,-120.85,NaN,NaN,NaN,NaN,-15.6,NaN,NaN,NaN,NaN,68.0,59.0,NaN,NaN,NaN,NaN
1062,2025-03-14 12:32:15,-118.05,-13.25,0.15,-121.2,NaN,NaN,NaN,NaN,-15.75,NaN,NaN,NaN,NaN,68.0,59.0,NaN,NaN,NaN,NaN
1063,2025-03-14 12:32:16,-118.15,-13.1,-1.05,-121.25,NaN,NaN,NaN,NaN,-15.65,NaN,NaN,NaN,NaN,68.0,59.0,NaN,NaN,NaN,NaN
1064,2025-03-14 12:32:17,-119.6,-13.6,-1.6,-121.85,NaN,NaN,NaN,NaN,-15.95,NaN,NaN,NaN,NaN,68.0,59.0,NaN,NaN,NaN,NaN

In [29]:
dl["NR_UE_NACK_Rate_UL_0"].unique()

array([  nan,   0. ,   2. ,   6.4,   1. ,   1.1,   0.5,   0.7,   0.8,
         1.5,   2.3,   2.2,   8.6,   1.3,   1.9,   0.9,   3.4,   4. ,
         4.1,   1.2,   2.4,   2.9,   4.7,   6.7,  14.7,   9.6,   9.5,
         5.6,  10.5,   7.3,   9.3,   9. ,   6.8,  12.4,   1.8,   4.3,
         6.3,   8.9,   6.9,  10.9,   8.5,   8.3,  15.7,  10.3,   6.6,
         3. ,   1.6,   0.6,   2.8,   8.8,  11.6,  10. ,   7.4,   7.5,
         9.8,   9.1,   7. ,  13.7,   7.2,   9.7,  10.2,   4.6,   5.3,
        11.5,  14. ,   8. ,  12.2,   8.4,  10.4,   7.6,   7.1,  11.2,
         3.5,   8.7,   4.5,  12. ,  11.3,  10.6,   8.2,   8.1,  10.1,
        20.1,   2.5,   2.6,   5.4,   9.2,  11. ,  16.6,   3.3,   4.8,
         2.1,   3.8,   3.2,  12.7,  11.8,  12.5,  50. ,   1.7,   1.4,
        14.2,   3.6,  11.4,   3.9,  10.7,   6.2,  11.1,   6. ,   4.4,
        15. ,  15.1,  20.3,  16.7,  16. ,  15.8,  10.8,   7.7,   7.9,
        16.2,  17.3,  13.3,  18.4,  12.9,  11.9,  11.7,  45.6,  29. ,
        24.5,  38.4,  15.5,  24.1,  24.6,  34.2,  31.9,   5.9,  12.1,
        13.4,  14.9,  21. ,  15.4,  20.2,  13. ,  20.5,  21.7,   7.8,
         9.9,  13.5,   9.4,  24.7,  14.4,  14.8,  18.1,  14.3,   5.2,
        12.8,  14.1,  16.3,  12.6,  15.2,  14.5,  15.6,  15.3,  17.7,
        17.5,  13.1,  17.6,  14.6,  16.9,  16.1,  16.4,  13.2,  13.6,
        27.2,  25.2,  18.5,  12.3,  13.8,  27.1,  28.6,  46.5,  56.9,
        51. ,  47.1,  52.3,  56. ,  60.9,  54.9,  45.8,  42.9,  48.7,
        55.7,  33.3,  50.3,  49.7,  54.2,  50.4,  54.4,  54.5,  19.4,
        26.4,  18.9,  30.1,  43.3,  66.7,  25. , 100. ,  20. ,  15.9,
        17.4,  17.9])

In [30]:
dl

,Message,Time,Longitude,Latitude,NR_UE_PCI_0,NR_UE_RSRP_0,NR_UE_RSRQ_0,NR_UE_SINR_0,NR_UE_Nbr_PCI_0,NR_UE_Nbr_PCI_1,...,NR_UE_RRCReEst_EndResult,NR_UE_RRCConnectionAttempt,NR_UE_RRCConnectionSetupOk,NR_UE_RRCConnectionComplete,NR_UE_RRCConnectionDrop,NR_UE_RRCHOAttempt,NR_UE_RRCHOOK,NR_RRC_MsgType,NAS_5GS_MM_MessageType,NAS_5GS_SM_MessageType
0,0,2025-03-14 12:14:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,NaN,NaN,NaN
1,1,2025-03-14 12:14:33,NaN,NaN,48.0,-87.1,-11.2,7.3,76.0,NaN,...,NaN,0,0,0,0,0,0,NaN,NaN,NaN
2,2,2025-03-14 12:14:33,29.02949,41.10723,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,NaN,NaN,NaN
3,3,2025-03-14 12:14:33,29.02949,41.10723,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,NaN,NaN,NaN
4,4,2025-03-14 12:14:33,29.02949,41.10723,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72475,72475,2025-03-14 12:32:17,29.02143,41.10031,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,NaN,NaN,NaN
72476,72476,2025-03-14 12:32:17,29.02143,41.10031,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,NaN,NaN,NaN
72477,72477,2025-03-14 12:32:17,29.02143,41.10031,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,NaN,NaN,NaN
72478,72478,2025-03-14 12:32:17,29.02143,41.10031,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,NaN,NaN,NaN
72479,72479,2025-03-14 12:32:17,29.02143,41.10031,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,0,0,0,NaN,NaN,NaN

In [31]:
dl.shape

(72480, 54)

In [38]:
dl.drop_duplicates(license=False).shape

TypeError: DataFrame.drop_duplicates() got an unexpected keyword argument 'license'